DROP TABLE IF EXISTS TAB1;
--Create Table Binary XML
CREATE TABLE IF NOT EXISTS TAB1 oF XMLTYPE
XMLTYPE STORE AS TRANSPORTABLE BINARY XML;

DROP TABLE IF EXISTS TAB2;
CREATE TABLE IF NOT EXISTS TAB2
 (
    id NUMBER,
    doc XMLTYPE
)
XMLTYPE COLUMN doc store as TRANSPORTABLE BINARY XML;