ALTER SESSION SET GROUP_BY_POSITION_ENABLED=FALSE;

SELECT to_char(hiredate,'MM') HIRE_MONTH
      ,count(empno) EMP_COUNT 
  FROM emp
 GROUP BY 1
  ORDER BY EMP_COUNT DESC
 OFFSET 0 ROWS
 FETCH NEXT 1 ROWS ONLY;

ALTER SESSION SET GROUP_BY_POSITION_ENABLED=TRUE;

SELECT to_char(hiredate,'MM') HIRE_MONTH
      ,count(empno) EMP_COUNT 
  FROM emp
 GROUP BY 1
  ORDER BY EMP_COUNT DESC
 OFFSET 0 ROWS
 FETCH NEXT 1 ROWS ONLY;

SELECT to_char(hiredate,'MM') HIRE_MONTH
      ,count(empno) EMP_COUNT 
  FROM emp
 GROUP BY HIRE_MONTH
  ORDER BY EMP_COUNT DESC
 OFFSET 0 ROWS
 FETCH NEXT 1 ROWS ONLY;

 SELECT to_char(hiredate,'MM') HIRE_MONTH
      ,count(empno) EMP_COUNT 
  FROM emp
 GROUP BY HIRE_MONTH
 HAVING HIRE_MONTH  IN ('04','07','10','01')
 ORDER BY EMP_COUNT DESC;
